# Generated by Django 4.1.1 on 2022-09-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brtr', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
