# Generated by Django 4.1.1 on 2022-09-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brtr', '0002_alter_order_status_alter_product_delivery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='for_sale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='trade',
            new_name='for_trade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_options',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_options',
            field=models.ManyToManyField(to='brtr.delivery_choices'),
        ),
    ]
