# Generated by Django 4.1.1 on 2022-09-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brtr', '0004_rename_delivery_choices_deliverychoices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('buy', 'Buy'), ('trade', 'Trade')], max_length=100),
        ),
    ]
